import { useState } from 'react'
import { Sparkles, ChevronDown, ChevronUp, ExternalLink, Info } from 'lucide-react'

interface Props {
  synthesis: string | null
  target: string
  disease: string
}

export function LLMSynthesis({ synthesis, target, disease }: Props) {
  const [expanded, setExpanded] = useState(true)

  if (!synthesis) return null

  // Bold **text** patterns
  const renderMarkdown = (text: string) => {
    const parts = text.split(/(\*\*[^*]+\*\*)/g)
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="text-ink font-semibold">{part.slice(2, -2)}</strong>
      }
      return <span key={i}>{part}</span>
    })
  }

  const paragraphs = synthesis.split('\n\n').filter(Boolean)

  return (
    <div className="card space-y-4">
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-2">
          <Sparkles size={14} className="text-teal" />
          <p className="label-mono">AI synthesis</p>
          <span className="text-xs text-ink-3 font-mono">claude-3-5-sonnet</span>
        </div>
        <button
          onClick={() => setExpanded((v) => !v)}
          className="flex items-center gap-1 text-xs text-ink-3 hover:text-ink-2 transition-colors"
        >
          {expanded ? <><ChevronUp size={12} /> Collapse</> : <><ChevronDown size={12} /> Expand</>}
        </button>
      </div>

      {/* Disclaimer */}
      <div className="flex items-start gap-2 p-3 rounded-lg bg-surface-2 border border-border">
        <Info size={13} className="text-ink-3 mt-0.5 flex-shrink-0" />
        <p className="text-xs text-ink-3 leading-relaxed">
          This synthesis is generated by an LLM from structured data returned by the 6 sources above.
          All factual claims are derived from primary database outputs. Click source links to verify independently.
          Not a substitute for expert scientific or regulatory review.
        </p>
      </div>

      {/* Content */}
      {expanded && (
        <div className="space-y-3">
          {paragraphs.map((para, idx) => {
            const isHeading = para.startsWith('**') && para.endsWith('**')
            if (isHeading) {
              return (
                <h4 key={idx} className="text-sm font-semibold text-ink mt-4 first:mt-0">
                  {para.replace(/\*\*/g, '')}
                </h4>
              )
            }

            // Section-level heading like **EXECUTIVE SUMMARY**
            const headingMatch = para.match(/^\*\*([^*]+)\*\*$/)
            if (headingMatch) {
              return (
                <h4 key={idx} className="text-sm font-semibold text-ink pt-1">
                  {headingMatch[1]}
                </h4>
              )
            }

            return (
              <p key={idx} className="text-sm text-ink-2 leading-relaxed">
                {renderMarkdown(para)}
              </p>
            )
          })}
        </div>
      )}

      {/* Source attribution */}
      <div className="pt-2 border-t border-border flex flex-wrap items-center gap-2">
        <span className="text-xs text-ink-3">Synthesis grounded in:</span>
        {[
          { label: 'Open Targets', url: 'https://www.opentargets.org' },
          { label: 'ClinicalTrials.gov', url: 'https://clinicaltrials.gov' },
          { label: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov' },
          { label: 'UniProt', url: 'https://www.uniprot.org' },
          { label: 'Drugs@FDA', url: 'https://www.accessdata.fda.gov/scripts/cder/daf/' },
          { label: 'FDA Orange Book', url: 'https://www.accessdata.fda.gov/scripts/cder/ob/' },
        ].map((s) => (
          <a key={s.label} href={s.url} target="_blank" rel="noopener noreferrer" className="source-chip">
            {s.label} <ExternalLink size={9} />
          </a>
        ))}
      </div>
    </div>
  )
}
